# Generated by Django 3.0.6 on 2020-05-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_update_info_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_info',
            name='data',
            field=models.ImageField(default=0, upload_to='../data/BinFiles/'),
        ),
    ]
