# Generated by Django 3.0.6 on 2020-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20200513_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_info',
            name='data',
            field=models.ImageField(default=0, upload_to='BinFiles/'),
        ),
    ]
