# Generated by Django 3.0.6 on 2020-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20200513_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_info',
            name='data',
            field=models.FileField(default=0, upload_to='BinFiles/'),
        ),
    ]
